import { redirect } from "next/navigation";

import { ScreenHead } from "@/components/screen-head";
import { createDownloadUrl, getSubscription } from "@/lib/api/account";
import { getApiErrorMessage } from "@/lib/api/client";

async function requestDownload() {
  "use server";

  let url: string;
  try {
    ({ url } = await createDownloadUrl());
  } catch (error) {
    redirect(`/download?error=${encodeURIComponent(getApiErrorMessage(error))}`);
  }

  redirect(url);
}

export default async function DownloadPage({
  searchParams,
}: {
  searchParams: Promise<{ error?: string }>;
}) {
  const params = await searchParams;
  const subscription = await getSubscription();
  const hasAccess = subscription?.status === "active" || subscription?.status === "trialing";

  return (
    <>
      <ScreenHead
        eyebrow="download"
        title="Get the<br/>loader."
        lede="The portal asks the API for a short-lived signed download URL. If download signing is not configured yet, the API response is shown here."
      />

      <div className="screen-body">
        {params.error && (
          <div className="group">
            <div className="group__l">
              <h2 className="group__title">Download unavailable</h2>
            </div>
            <div className="group__r">
              <div className="rowlist">
                <div className="row">
                  <div className="row__main">
                    <div className="row__title">{params.error}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="group">
          <div className="group__l">
            <h2 className="group__title">Loader access</h2>
            <p className="group__caption">
              Subscription state is read from the API before presenting the
              download action.
            </p>
          </div>
          <div className="group__r">
            <div className="rowlist">
              <div className="form-row">
                <span className="form-row__label">status</span>
                <span className="form-row__val">
                  {subscription ? subscription.status : "No active plan"}
                </span>
                <span className={`tag ${hasAccess ? "tag--active" : "tag--off"}`}>
                  <span className="dot" />
                  {hasAccess ? "eligible" : "locked"}
                </span>
              </div>
              <div className="form-row">
                <span className="form-row__label">file</span>
                <span className="form-row__val form-row__val--muted">
                  Signed URL generated by POST /v1/download/url.
                </span>
                {hasAccess ? (
                  <form action={requestDownload}>
                    <button className="linkbtn" type="submit">
                      download
                    </button>
                  </form>
                ) : (
                  <span className="tag tag--off">
                    <span className="dot" />
                    subscribe first
                  </span>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
